### PR TITLE
Adding R code to the Repo

### PR DESCRIPTION
**Pull request by paulbessell**
R code for plotting outputs

### CODE REVIEW

**Comment by johnnonweiler** [comment]
Thank you, Paul!  I was very happy when I saw this PR appear.

**Comment by johnnonweiler** [comment]
I have now successfully run this code in RStudio and confirmed that it generates the images.

(The only thing that I had to do which wasn't immediately obvious was that I needed to `install.packages("ggpubr")` . RStudio successfully installed everything else required for me with a simple click, but for some reason this required an extra step.)

**Comment by BlairArchibald** [comment]
I agree it's great to have this in now and do any changes in later PRs (it all looks pretty sane from a glance, but I'm not an R expert - probably the only change that would be good in the short term is to have the inputFile as a commandline parameter to make it easier to integrate into workflows).

I am also for *not* adding the example files/figures, there's a lot of data and it's likely they go out of date very quickly.

**Comment by johnnonweiler** [comment]
I think there is a good case for having one example output file.  It includes data from 100 simulations on the HPC system, which is not trivial to replace.  I suggest we update it when we do a release (and not more often than that).

**Comment by johnnonweiler** [comment]
(I also like to have the images, which are useful for people who have not installed RStudio.)

**Pull request merged**
