### PR TITLE
Just tweaking some more parameters

### PR DESCRIPTION
**Pull request by paulbessell**
Workplace allocation has bene updated wiht data

### CODE REVIEW

**Comment by paulbessell** [comment]
@BlairArchibald Your PR is failing the same test, so mind if I leave this to you to sort out

**Comment by BlairArchibald** [comment]
Hopefully fixed if we merge https://github.com/ScottishCovidResponse/Covid_Simulation_Model/pull/85 first

**Comment by paulbessell** [comment]
@BlairArchibald Sorry to trouble oyu again Blair. Could you possibly take a look at MovementTest().newInfectionsResetIsolationTimer(). I don't know why it should be failing, I don't think I should have done anything to mess it up

**Comment by BlairArchibald** [comment]
That's possibly fixed in the hospitalisations branch so let's try merging that first? It seems to be one of these not-quite-robust to the RNG tests.

**Comment by paulbessell** [comment]
> That's possibly fixed in the hospitalisations branch so let's try merging that first? It seems to be one of these not-quite-robust to the RNG tests.

Yes. It is an annoying one that doesn't fail when I do `gradle test` but fails on github

**Comment by BlairArchibald** [comment]
I've merged this in. These new parameters seem to cause a lot of impossible worker allocations (I expect the tests will fail). I think this is probably something we need to address since it seems to highlight to we have too many/few of certain places. I can do a bit more digging soon so see exactly what isn't getting allocated!

**Comment by BlairArchibald** [comment]
Scratch that - there was a bug in the shop requirements

**Comment by BlairArchibald** [comment]
Not sure if these new errors are due to the new parameters - looks like too few people are dying.

**Pull request closed without merging**
